name: 'Build and push images'
description: 'Build and push container images'
inputs:
  registry:
    description: 'Disco host'
    required: true
  name:
    description: 'Name of container to build'
    required: true
  version:
    description: 'Forta scan node version'
    required: true
  prerelease:
    description: 'Is a prerelease'
    required: true
outputs:
  release-cid:
    description: 'IPFS CID of the release manifest'
    value: ${{ steps.build-and-push.outputs.release-cid }}
  image-reference:
    description: 'Reference of the built and pushed image'
    value: ${{ steps.build-and-push.outputs.image-reference }}
runs:
  using: "composite"
  steps:
    - name: Login to Forta Disco
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: discouser
        password: discopass
    - name: Build and push container
      id: build-and-push
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        IMAGE_NAME: ${{ inputs.name }}
        VERSION: ${{ inputs.version }}
        COMMIT_SHA: ${{ github.sha }}
        PRERELEASE: ${{ inputs.prerelease }}
      run: |
        IMAGE_REF=$(./scripts/docker-build-push.sh "$REGISTRY" "$IMAGE_NAME" "$COMMIT_SHA")
        echo "::set-output name=image-reference::$IMAGE_REF"
        go run ./scripts/go/releasemanifest/main.go --version "$VERSION" --commit-sha "$GITHUB_SHA" --node-image "$IMAGE_REF" --is-prerelease "$PRERELEASE"
        MANIFEST_REF=$(./scripts/ipfs-add.sh "./manifest.json")
        echo "::set-output name=release-cid::$MANIFEST_REF"
